from django.urls import path

from . import views

urlpatterns = [path("index.html", views.index, name="index"),	      
			path("AdminLogin.html", views.AdminLogin, name="AdminLogin"),
			path("AdminLoginAction", views.AdminLoginAction, name="AdminLoginAction"),
			path("AddDoctor.html", views.AddDoctor, name="AddDoctor"),
			path("AddDoctorAction", views.AddDoctorAction, name="AddDoctorAction"),
			path("ViewAdminDoctor", views.ViewAdminDoctor, name="ViewAdminDoctor"),
			path("ViewAdminAppointments", views.ViewAdminAppointments, name="ViewAdminAppointments"),
			path("ViewAdminPatients", views.ViewAdminPatients, name="ViewAdminPatients"),
			path("ViewAdminDonors", views.ViewAdminDonors, name="ViewAdminDonors"),
			path("PatientSignup", views.PatientSignup, name="PatientSignup"),
			path("PatientSignupAction", views.PatientSignupAction, name="PatientSignupAction"),
			path("PatientLogin.html", views.PatientLogin, name="PatientLogin"),
			path("PatientLoginAction", views.PatientLoginAction, name="PatientLoginAction"),
			path("BookAppointment.html", views.BookAppointment, name="BookAppointment"),
			path("BookAppointmentAction", views.BookAppointmentAction, name="BookAppointmentAction"),
			path("ConfirmAppointment", views.ConfirmAppointment, name="ConfirmAppointment"),
			path("ConfirmAppointmentAction", views.ConfirmAppointmentAction, name="ConfirmAppointmentAction"),
			path("ViewMyPatientDetails", views.ViewMyPatientDetails, name="ViewMyPatientDetails"),
			path("ViewPatientAppointment", views.ViewPatientAppointment, name="ViewPatientAppointment"),
			path("CancelAppointment", views.CancelAppointment, name="CancelAppointment"),
			path("DonateOrgan", views.DonateOrgan, name="DonateOrgan"),
			path("DonateOrganAction", views.DonateOrganAction, name="DonateOrganAction"),
			path("Feedback", views.Feedback, name="Feedback"),
			path("FeedbackAction", views.FeedbackAction, name="FeedbackAction"),
			path("SearchOrgan", views.SearchOrgan, name="SearchOrgan"),
			path("DoctorLogin.html", views.DoctorLogin, name="DoctorLogin"),
			path("DoctorLoginAction", views.DoctorLoginAction, name="DoctorLoginAction"),
			path("ViewDoctorDetails", views.ViewDoctorDetails, name="ViewDoctorDetails"),
			path("ViewDoctorAppointment", views.ViewDoctorAppointment, name="ViewDoctorAppointment"),
			path("GeneratePrescription", views.GeneratePrescription, name="GeneratePrescription"),
			path("GeneratePrescriptionAction", views.GeneratePrescriptionAction, name="GeneratePrescriptionAction"),
			path("ViewAdminAppointments", views.ViewAdminAppointments, name="ViewAdminAppointments"),
			path("ViewAdminPatients", views.ViewAdminPatients, name="ViewAdminPatients"),
			path("ViewAdminDonors", views.ViewAdminDonors, name="ViewAdminDonors"),
			path("ViewAdminFeedback", views.ViewAdminFeedback, name="ViewAdminFeedback"),
]